### ISSUE TITLE
 Class "default" not found

### ISSUE THREAD

**Issue by adrav** [symplify/easy-ci#6]
**Affected version:**
 symplify/easy-ci 11.2.0.72

**Problem:**
Easy-ci does not handle the "default" parameter in %env.

**How to reproduce:**

1. Create yml file with the following content:

```
parameters:
    some_parameter: '%env(default::MY_PARAMETER)%'
```
According to the Symfony documentation: "When the fallback parameter is omitted (e.g. env(default::API_KEY)), then the returned value is null."
https://symfony.com/doc/current/configuration/env_var_processors.html

2. Execute 
`php8.1 vendor/bin/easy-ci check-config src`

3. The following error will be printed out:

```
src/MyBundle/Resources/config/services.yml
 * Class "default" not found
```

**Bug:**
I think bug is in the following regex:
`private const STATIC_CALL_CLASS_REGEX = '#(?<quote>["\']?)[\\\\]*(?<class_name>[A-Za-z][\\w\\\\]+)::#';`
in file:
`Symplify\EasyCI\Config\ClassExtractor`

**Notes:**
https://regex101.com/r/gjZUkS/1

**Comment by TomasVotruba** [comment]
Thanks for detailed report!

Could you propose a fix and test fixture, so we have it covered?

**Comment by adrav** [comment]
Please check my quickfix:

https://github.com/adrav/easy-ci/commit/932d63f72326adeb6aea637b478eef6047d1f228

regex test: https://regex101.com/r/m5T34R/1

**Comment by TomasVotruba** [comment]
Send it as PR please

**Comment by adrav** [comment]
I am not able to send it as PR because 11.2.0.72 is a tag and commit "does not belong to any branch on this repository, and may belong to a fork outside of the repository." This is the message from Github.

https://github.com/symplify/easy-ci/tree/11.2.0.72

**Comment by TomasVotruba** [comment]
Always aim for main branch

**Comment by TomasVotruba** [comment]
Closing for lack of feedback. Feel free to send PR with a fix if you find one :+1:
