### ISSUE TITLE
Fail to detect commented code

### ISSUE THREAD

**Issue by UksusoFF** [symplify/easy-ci#7]
![image](https://user-images.githubusercontent.com/1931442/227165743-491a01f2-c423-4aae-8f61-318d7012e4d8.png)

**Comment by TomasVotruba** [comment]
What line limit did you setup?

See https://github.com/symplify/easy-ci#5-detect-commented-code

**Comment by UksusoFF** [comment]
DEFAULT_LINE_LIMIT

**Comment by TomasVotruba** [comment]
There are just 3 lines tops in your code.  4 lines would do :)

```php
// line
// line
// line
// line
```

The `/* */` is not supported, as it's very costly to make it right and slow.

**Comment by UksusoFF** [comment]
Ouch so we need decrease line limit? 
When we use 1 it's detect comments too. But this comments not contains code.
